// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIIf1tX6GTcBut3KX263XZulGCjn0cgQ8',
    appId: '1:981000386729:web:9980bf8a1a9434c16ed1b8',
    messagingSenderId: '981000386729',
    projectId: 'final-2025-f278f',
    authDomain: 'final-2025-f278f.firebaseapp.com',
    storageBucket: 'final-2025-f278f.firebasestorage.app',
    measurementId: 'G-6JKCDS63YN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4fch4maOU1zt5fKGquYYBDS9KDN7p7qE',
    appId: '1:981000386729:android:4f022652616e1abc6ed1b8',
    messagingSenderId: '981000386729',
    projectId: 'final-2025-f278f',
    storageBucket: 'final-2025-f278f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGAo2o6r58Yabkf2r71EYWFJhv04wwLgY',
    appId: '1:981000386729:ios:c2d6484f1ad618b16ed1b8',
    messagingSenderId: '981000386729',
    projectId: 'final-2025-f278f',
    storageBucket: 'final-2025-f278f.firebasestorage.app',
    iosBundleId: 'com.example.final2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGAo2o6r58Yabkf2r71EYWFJhv04wwLgY',
    appId: '1:981000386729:ios:c2d6484f1ad618b16ed1b8',
    messagingSenderId: '981000386729',
    projectId: 'final-2025-f278f',
    storageBucket: 'final-2025-f278f.firebasestorage.app',
    iosBundleId: 'com.example.final2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIIf1tX6GTcBut3KX263XZulGCjn0cgQ8',
    appId: '1:981000386729:web:2241c404dda085e16ed1b8',
    messagingSenderId: '981000386729',
    projectId: 'final-2025-f278f',
    authDomain: 'final-2025-f278f.firebaseapp.com',
    storageBucket: 'final-2025-f278f.firebasestorage.app',
    measurementId: 'G-300TBYN1Y8',
  );
}
